name: cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: 2.9.1

# Add regular dependencies here.
dependencies:
  analyzer: ^6.3.0

dev_dependencies:
  lints: ^2.5.0
  test: ^2.15.0
