name: cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^2.12.0

dependencies:
  analyzer: ^2.3.0

dev_dependencies:
  lints: 0.1.0
  test: ^1.0.0
