version: 2.1

orbs:
  win: circleci/windows@2.4.0

aliases:
  - &project_dir "~/project"

commands:
  dependencies:
    description: "Download dependencies and setup global packages"
    parameters:
      shell:
        type: string
        default: "/bin/bash --login -eo pipefail"
      pub-cache:
        type: string
        default: "~/.pub-cache"
    steps:
      - checkout
      - run:
          name: go to dart directory
          shell: << parameters.shell >>
          command: cd dart && cd cli && ls
      - run:
          name: Download deps
          shell: << parameters.shell >>
          command: cd dart && cd cli && ls && pub get

workflows:
  version: 2.1
  test-and-build:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: google/dart:2.15.0
    steps:
      - checkout
      - dependencies:
          shell: "/bin/bash -eo pipefail"
      - run:
          name: Make folder for test results
          command: mkdir -p test-results/dart-tests
      - run:
          name: Run tests
          command: cd dart && cd cli && pub run test
      - store_test_results:
          path: test-results
      - run:
          name: Run analysis linter
          command: cd dart && cd cli && dart analyze dart/cli/bin/rice_cooker.dart

